version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependabot"
    assignees:
      - "joshjohanning"
    reviewers:
      - "joshjohanning"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependabot"
    assignees:
      - "joshjohanning"
    reviewers:
      - "joshjohanning"
